environment = "staging"

[api_config]
bybit_api_key = "your_api_key_here"
bybit_api_secret = "your_api_secret_here"
use_demo = true
rate_limit_requests_per_minute = 120
connection_timeout = 30
request_timeout = 10

[trading_config]
total_capital = 12.0
max_risk_per_trade = 1.0
max_portfolio_risk = 5.0
min_confidence = 80.0
max_positions = 5
trading_enabled = true

[monitoring_config]
enabled = true
collection_interval = 60
health_check_interval = 300

[monitoring_config.alert_thresholds]
max_cpu_usage = 80.0
max_memory_usage = 85.0
max_api_latency = 5000.0
max_analysis_time = 10000.0
max_error_rate = 5.0
min_cache_hit_rate = 80.0

[safety_config]
emergency_stop_enabled = true
max_daily_loss = 2.0
max_consecutive_losses = 3
circuit_breaker_enabled = true
auto_recovery_enabled = false

[logging_config]
level = "debug"
log_to_file = true
log_file_path = "logs/omni.log"
rotation_enabled = true
max_file_size_mb = 100
